source 'https://rubygems.org'

gem 'escape_utils', '~> 1.0.1'

# for rake spec
#gem 'rake', '~> 10.3.2'
#gem 'rspec', '~> 3.0.0'
gem 'test-unit'
gem 'rspec'
gem 'watir-webdriver'
gem 'rake'
gem 'rspec-rerun'
gem 'pony'
gem 'slack-notifier'
gem 'multi_json'
gem 'thor'
gem 'open_uri_redirections'
gem 'rspec-core'
gem 'touch_action'
gem 'appium_lib'